import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Head from 'next/head'
import NavBar from "./NavBar";
import { cookies } from 'next/headers'
import { ObjectId } from 'bson';
import { PrismaClient } from '@prisma/client';
import SetCookie from './cookie';

const prisma = new PrismaClient();

const mont = Montserrat({ 
  subsets: ['latin'],
  variable: "--font-mont"
})
export const metadata: Metadata = {
  title: 'StoreApp',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const name = cookies().get("user")
  var newName = "";
  if(!name){
    newName = new ObjectId() as unknown  as string;
    await prisma.users.create({
      data: {
        id: newName,
        cart: [],
        sorting: {"Filter":"","Sort":"","min":"","max":""}
      }
    })
  }
  if(name){
    const user = await prisma.users.findUnique({
      where: {
        id:name.value
      }
    })
    if(!user){
      await prisma.users.create({
        data: {
          id: name.value,
          cart: [],
          sorting: {"Filter":"","Sort":"","min":"","max":""}
        }
      })
    }
  }
  return (
    
    <html lang="en">
      
      <body className={`${mont.variable} font-mont bg-cream`}>
        {!name &&  <SetCookie name="user" value={newName}/>}
        <NavBar/>
        <main className='bg-cream'>{children}</main>
      </body>
    </html>
  )
}
